# shelter dataset here

dataset_url: "https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/21c83b32-d5a8-4106-a54f-010dbe49f6f2/resource/79723018-8dc7-4cd4-8fb4-8652376ea531/download/daily-shelter-overnight-service-occupancy-capacity-2023.csv"


plot_color: 'r'